version: '3'
services:
    db:
        image: postgres:9.4
        restart: always
        ports:
            - 5432
        volumes:
            - "./db:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong

    kong:
        build: .
        image: kong
        restart: always
        links:
            - db
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
        expose:
            - 7946
            - 7946/udp
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=db
        volumes:
            - ./kong.conf:/etc/kong/kong.conf
            - ./logs:/usr/local/kong/logs